openapi: 3.0.0
info:
  title: Hello World API
  description: A simple API that says Hello World!
  version: 1.0.0
servers:
  - url: https://example.com/api/v1
    description: Production server
  - url: http://localhost:3000
    description: Local development server
paths:
  /hello:
    get:
      summary: Say Hello
      description: Returns a simple "Hello World" message.
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
