export const olympicEvents: string[] = [
    "Basketball Men's Basketball",
    "Judo Men's Extra-Lightweight",
    "Football Men's Football",
    "Tug-Of-War Men's Tug-Of-War",
    "Athletics Women's 100 metres",
    "Athletics Women's 4 x 100 metres Relay",
    "Swimming Men's 400 metres Freestyle",
    "Badminton Men's Singles",
    "Sailing Women's Windsurfer",
    "Swimming Men's 200 metres Breaststroke",
    "Swimming Men's 400 metres Breaststroke",
    "Gymnastics Men's Individual All-Around",
    "Gymnastics Men's Team All-Around",
    "Gymnastics Men's Floor Exercise",
    "Gymnastics Men's Horse Vault",
    "Gymnastics Men's Parallel Bars",
    "Gymnastics Men's Horizontal Bar",
    "Gymnastics Men's Rings",
    "Gymnastics Men's Pommelled Horse",
    "Athletics Men's Shot Put",
    "Art Competitions Mixed Sculpturing, Unknown Event",
    "Handball Women's Handball",
    "Weightlifting Women's Super-Heavyweight",
    "Wrestling Men's Light-Heavyweight, Greco-Roman",
    "Gymnastics Men's Team All-Around, Free System",
    "Water Polo Men's Water Polo",
    "Sailing Mixed Three Person Keelboat",
    "Hockey Women's Hockey",
    "Rowing Men's Lightweight Double Sculls",
    "Athletics Men's Pole Vault",
    "Athletics Men's High Jump",
    "Sailing Men's Two Person Dinghy",
    "Athletics Men's 1,500 metres",
    "Swimming Men's 100 metres Butterfly",
    "Swimming Men's 200 metres Butterfly",
    "Swimming Men's 4 x 100 metres Medley Relay",
    "Football Women's Football",
    "Fencing Men's Foil, Individual",
    "Fencing Men's epee, Individual",
    "Fencing Men's epee, Team",
    "Sailing Mixed 8 metres",
    "Equestrianism Mixed Jumping, Individual",
    "Shooting Men's Small-Bore Rifle, Prone, 50 metres",
    "Shooting Men's Rapid-Fire Pistol, 25 metres",
    "Shooting Men's Trap",
    "Athletics Men's 4 x 100 metres Relay",
    "Athletics Men's Long Jump",
    "Boxing Men's Light-Welterweight",
    "Athletics Women's Javelin Throw",
    "Wrestling Men's Heavyweight, Freestyle",
    "Taekwondo Men's Flyweight",
    "Boxing Men's Heavyweight",
    "Athletics Men's 5,000 metres",
    "Cycling Men's Road Race, Individual",
    "Cycling Men's Road Race, Team",
    "Weightlifting Men's Lightweight",
    "Weightlifting Men's Middleweight",
    "Rowing Men's Coxless Pairs",
    "Judo Men's Half-Middleweight",
    "Taekwondo Women's Flyweight",
    "Boxing Men's Flyweight",
    "Basketball Women's Basketball",
    "Diving Men's Platform",
    "Canoeing Men's Canadian Doubles, 500 metres",
    "Canoeing Men's Canadian Doubles, 1,000 metres",
    "Canoeing Men's Kayak Fours, 1,000 metres",
    "Handball Men's Handball",
    "Rowing Women's Coxless Pairs",
    "Boxing Men's Middleweight",
    "Judo Men's Lightweight",
    "Boxing Men's Featherweight",
    "Tennis Men's Doubles",
    "Shooting Mixed Skeet",
    "Wrestling Men's Featherweight, Freestyle",
    "Sailing Mixed Two Person Heavyweight Dinghy",
    "Athletics Women's Shot Put",
    "Rowing Men's Coxed Eights",
    "Cycling Women's Sprint",
    "Cycling Women's 500 metres Time Trial",
    "Athletics Men's 110 metres Hurdles",
    "Shooting Mixed Trap",
    "Athletics Women's Marathon",
    "Athletics Men's 100 metres",
    "Fencing Men's Foil, Team",
    "Fencing Men's Sabre, Team",
    "Swimming Men's 100 metres Freestyle",
    "Swimming Men's 4 x 200 metres Freestyle Relay",
    "Boxing Men's Lightweight",
    "Modern Pentathlon Men's Individual",
    "Boxing Men's Welterweight",
    "Rowing Men's Quadruple Sculls",
    "Rowing Men's Double Sculls",
    "Rowing Men's Coxed Pairs",
    "Athletics Men's 400 metres Hurdles",
    "Athletics Men's 400 metres",
    "Athletics Men's Hammer Throw",
    "Weightlifting Men's Featherweight",
    "Athletics Men's 800 metres",
    "Hockey Men's Hockey",
    "Rowing Women's Single Sculls",
    "Swimming Men's 50 metres Freestyle",
    "Weightlifting Women's Featherweight",
    "Water Polo Women's Water Polo",
    "Weightlifting Men's Heavyweight",
    "Equestrianism Mixed Three-Day Event, Individual",
    "Equestrianism Mixed Three-Day Event, Team",
    "Sailing Women's Three Person Keelboat",
    "Cycling Women's Road Race, Individual",
    "Golf Women's Individual",
    "Softball Women's Softball",
    "Archery Women's Individual",
    "Wrestling Men's Heavyweight, Greco-Roman",
    "Volleyball Men's Volleyball",
    "Taekwondo Women's Heavyweight",
    "Synchronized Swimming Women's Duet",
    "Synchronized Swimming Women's Team",
    "Taekwondo Women's Featherweight",
    "Athletics Men's Marathon",
    "Athletics Men's 4 x 400 metres Relay",
    "Athletics Men's 10,000 metres",
    "Athletics Women's 3,000 metres",
    "Diving Women's Platform",
    "Shooting Men's Air Rifle, 10 metres",
    "Athletics Men's 200 metres",
    "Weightlifting Men's Flyweight",
    "Swimming Men's 100 metres Backstroke",
    "Weightlifting Men's Light-Heavyweight",
    "Wrestling Men's Lightweight, Greco-Roman",
    "Fencing Men's Sabre, Individual",
    "Wrestling Men's Super-Heavyweight, Greco-Roman",
    "Shooting Men's Free Pistol, 50 metres",
    "Shooting Men's Air Pistol, 10 metres",
    "Rowing Men's Coxless Fours",
    "Boxing Men's Light-Flyweight",
    "Boxing Men's Super-Heavyweight",
    "Wrestling Men's Flyweight, Greco-Roman",
    "Shooting Women's Air Rifle, 10 metres",
    "Weightlifting Men's Middle-Heavyweight",
    "Athletics Men's Javelin Throw",
    "Volleyball Women's Volleyball",
    "Wrestling Men's Welterweight, Greco-Roman",
    "Wrestling Men's Middleweight, Greco-Roman",
    "Athletics Men's 3,000 metres Steeplechase",
    "Wrestling Men's Middleweight, Freestyle",
    "Swimming Women's 100 metres Backstroke",
    "Swimming Women's 200 metres Backstroke",
    "Swimming Women's 4 x 100 metres Medley Relay",
    "Wrestling Men's Light-Heavyweight, Freestyle",
    "Modern Pentathlon Men's Team",
    "Boxing Men's Bantamweight",
    "Athletics Women's 200 metres",
    "Table Tennis Women's Singles",
    "Table Tennis Women's Doubles",
    "Shooting Men's Skeet",
    "Swimming Women's 50 metres Freestyle",
    "Shooting Men's Small-Bore Rifle, Three Positions, 50 metres",
    "Athletics Men's Triple Jump",
    "Weightlifting Women's Lightweight",
    "Athletics Women's Long Jump",
    "Fencing Women's epee, Individual",
    "Swimming Men's 200 metres Freestyle",
    "Swimming Men's 4 x 100 metres Freestyle Relay",
    "Swimming Men's 200 metres Backstroke",
    "Swimming Men's 200 metres Individual Medley",
    "Swimming Men's 400 metres Individual Medley",
    "Badminton Women's Singles",
    "Boxing Men's Light-Middleweight",
    "Tennis Men's Singles",
    "Wrestling Men's Bantamweight, Freestyle",
    "Wrestling Men's Flyweight, Freestyle",
    "Athletics Women's 5,000 metres",
    "Weightlifting Women's Light-Heavyweight",
    "Weightlifting Women's Heavyweight",
    "Athletics Men's Discus Throw",
    "Taekwondo Men's Featherweight",
    "Taekwondo Men's Welterweight",
    "Judo Men's Heavyweight",
    "Cycling Men's Sprint",
    "Wrestling Men's Lightweight, Freestyle",
    "Baseball Men's Baseball",
    "Rowing Men's Coxed Fours",
    "Cycling Men's 100 kilometres Team Time Trial",
    "Rhythmic Gymnastics Women's Group",
    "Art Competitions Mixed Architecture, Designs For Town Planning",
    "Art Competitions Mixed Architecture, Architectural Designs",
    "Gymnastics Women's Individual All-Around",
    "Gymnastics Women's Team All-Around",
    "Gymnastics Women's Floor Exercise",
    "Gymnastics Women's Horse Vault",
    "Gymnastics Women's Uneven Bars",
    "Gymnastics Women's Balance Beam",
    "Diving Women's Springboard",
    "Diving Women's Synchronized Springboard",
    "Athletics Women's 10,000 metres",
    "Sailing Mixed 7 metres",
    "Judo Women's Half-Middleweight",
    "Athletics Men's Decathlon",
    "Wrestling Men's Middleweight A, Greco-Roman",
    "Athletics Women's Discus Throw",
    "Swimming Women's 4 x 100 metres Freestyle Relay",
    "Athletics Women's 1,500 metres",
    "Shooting Women's Air Pistol, 10 metres",
    "Shooting Women's Sporting Pistol, 25 metres",
    "Canoeing Men's Kayak Doubles, 500 metres",
    "Canoeing Men's Kayak Singles, 500 metres",
    "Canoeing Men's Kayak Singles, 1,000 metres",
    "Shooting Men's Running Target, 50 metres",
    "Judo Women's Half-Heavyweight",
    "Athletics Women's Pole Vault",
    "Rugby Sevens Women's Rugby Sevens",
    "Table Tennis Men's Team",
    "Rowing Women's Coxed Eights",
    "Athletics Women's 4 x 400 metres Relay",
    "Cycling Men's 1,000 metres Time Trial",
    "Cycling Men's Individual Pursuit, 4,000 metres",
    "Wrestling Men's Welterweight, Freestyle",
    "Wrestling Men's Bantamweight, Greco-Roman",
    "Rowing Women's Lightweight Double Sculls",
    "Athletics Women's 800 metres",
    "Rowing Women's Coxed Quadruple Sculls",
    "Rhythmic Gymnastics Women's Individual",
    "Canoeing Men's Kayak Singles, Slalom",
    "Archery Men's Individual",
    "Archery Men's Team",
    "Athletics Women's 400 metres",
    "Trampolining Men's Individual",
    "Beach Volleyball Men's Beach Volleyball",
    "Cycling Women's Mountainbike, Cross-Country",
    "Athletics Men's Javelin Throw, Both Hands",
    "Triathlon Women's Olympic Distance",
    "Gymnastics Women's Team Portable Apparatus",
    "Cycling Men's Mountainbike, Cross-Country",
    "Athletics Women's 400 metres Hurdles",
    "Diving Men's Springboard",
    "Wrestling Men's Featherweight, Greco-Roman",
    "Table Tennis Men's Singles",
    "Art Competitions Mixed Painting",
    "Judo Men's Open Class",
    "Rowing Women's Quadruple Sculls",
    "Gymnastics Men's Team All-Around, Swedish System",
    "Athletics Women's Pentathlon",
    "Art Competitions Mixed Painting, Unknown Event",
    "Cycling Men's Team Pursuit, 4,000 metres",
    "Weightlifting Women's Middleweight",
    "Swimming Men's 1,500 metres Freestyle",
    "Wrestling Women's Light-Heavyweight, Freestyle",
    "Swimming Women's 100 metres Freestyle",
    "Equestrianism Men's Jumping, Individual",
    "Equestrianism Men's Jumping, Team",
    "Equestrianism Men's Three-Day Event, Individual",
    "Equestrianism Men's Three-Day Event, Team",
    "Athletics Women's High Jump",
    "Canoeing Women's Kayak Fours, 500 metres",
    "Sailing Men's One Person Dinghy",
    "Trampolining Women's Individual",
    "Art Competitions Mixed Literature",
    "Judo Men's Middleweight",
    "Judo Men's Half-Lightweight",
    "Fencing Women's Foil, Team",
    "Swimming Women's 200 metres Butterfly",
    "Swimming Women's 400 metres Individual Medley",
    "Golf Men's Individual",
    "Athletics Men's Standing High Jump",
    "Athletics Men's Standing Long Jump",
    "Athletics Men's 20 kilometres Walk",
    "Swimming Men's 220 yard Freestyle",
    "Swimming Men's 880 yard Freestyle",
    "Swimming Men's One Mile Freestyle",
    "Swimming Men's 4 x 50 Yard Freestyle Relay",
    "Swimming Men's Plunge For Distance",
    "Shooting Men's Free Rifle, Three Positions, 300 metres",
    "Shooting Men's Military Rifle, Three Positions, 300 metres",
    "Shooting Men's Military Rifle, Any Position, 600 metres",
    "Shooting Men's Military Rifle, 200, 400, 500 and 600 metres, Team",
    "Shooting Men's Military Rifle, Prone, 300 metres",
    "Judo Men's Half-Heavyweight",
    "Archery Women's Team",
    "Athletics Men's 50 kilometres Walk",
    "Rowing Women's Double Sculls",
    "Sailing Mixed 6 metres",
    "Boxing Men's Light-Heavyweight",
    "Boxing Women's Flyweight",
    "Athletics Women's 100 metres Hurdles",
    "Athletics Men's Discus Throw, Greek Style",
    "Sailing Mixed One Person Dinghy",
    "Wrestling Women's Heavyweight, Freestyle",
    "Badminton Mixed Doubles",
    "Fencing Women's Foil, Individual",
    "Sailing Mixed Two Person Keelboat",
    "Shooting Men's Military Rifle, 300 metres and 600 metres, Prone, Team",
    "Table Tennis Men's Doubles",
    "Wrestling Men's Light-Flyweight, Freestyle",
    "Wrestling Women's Featherweight, Freestyle",
    "Swimming Women's 200 metres Freestyle",
    "Swimming Women's 400 metres Freestyle",
    "Swimming Women's 200 metres Individual Medley",
    "Sailing Men's Windsurfer",
    "Shooting Men's Running Target, Single Shot",
    "Shooting Men's Running Target, Double Shot",
    "Rugby Sevens Men's Rugby Sevens",
    "Wrestling Women's Lightweight, Freestyle",
    "Modern Pentathlon Women's Individual",
    "Canoeing Men's Canadian Doubles, Slalom",
    "Judo Women's Half-Lightweight",
    "Diving Women's Plain High",
    "Equestrianism Men's Dressage, Individual",
    "Equestrianism Men's Dressage, Team",
    "Tennis Women's Singles, Covered Courts",
    "Diving Men's Plain High",
    "Shooting Mixed Small-Bore Rifle, Three Positions, 50 metres",
    "Shooting Mixed Small-Bore Rifle, Prone, 50 metres",
    "Swimming Women's 800 metres Freestyle",
    "Sailing Women's Two Person Dinghy",
    "Shooting Men's Free Pistol, 50 metres, Team",
    "Shooting Men's Free Rifle, Three Positions, 300 metres, Team",
    "Shooting Men's Military Rifle, Prone, 300 metres, Team",
    "Shooting Men's Military Rifle, Prone, 600 metres, Team",
    "Shooting Men's Military Rifle, Standing, 300 metres, Team",
    "Shooting Men's Free Rifle, Prone, 600 metres",
    "Shooting Men's Free Rifle, 400, 600 and 800 metres, Team",
    "Rowing Men's Single Sculls",
    "Cycling Men's Tandem Sprint, 2,000 metres",
    "Athletics Women's Heptathlon",
    "Cycling Men's Points Race",
    "Synchronized Swimming Women's Solo",
    "Equestrianism Mixed Dressage, Individual",
    "Equestrianism Mixed Dressage, Team",
    "Swimming Men's 100 metres Breaststroke",
    "Shooting Mixed Free Pistol, 50 metres",
    "Sailing Women's Skiff",
    "Canoeing Men's Kayak Doubles, 10,000 metres",
    "Triathlon Men's Olympic Distance",
    "Sailing Women's One Person Dinghy",
    "Rowing Men's 17-Man Naval Rowing Boats",
    "Beach Volleyball Women's Beach Volleyball",
    "Weightlifting Men's Super-Heavyweight",
    "Rowing Men's Lightweight Coxless Fours",
    "Wrestling Men's Light-Flyweight, Greco-Roman",
    "Canoeing Men's Canadian Singles, 1,000 metres",
    "Sailing Mixed 5.5 metres",
    "Equestrianism Mixed Jumping, Team",
    "Diving Men's Synchronized Platform",
    "Canoeing Women's Kayak Singles, Slalom",
    "Weightlifting Women's Flyweight",
    "Swimming Women's 100 metres Breaststroke",
    "Swimming Women's 200 metres Breaststroke",
    "Wrestling Men's Middleweight B, Greco-Roman",
    "Athletics Men's Stone Throw",
    "Athletics Men's Javelin Throw, Freestyle",
    "Athletics Men's Pentathlon (Ancient)",
    "Shooting Women's Small-Bore Rifle, Three Positions, 50 metres",
    "Swimming Women's 100 metres Butterfly",
    "Weightlifting Men's Heavyweight I",
    "Athletics Women's 3,000 metres Steeplechase",
    "Athletics Men's Shot Put, Both Hands",
    "Shooting Women's Trap",
    "Badminton Men's Doubles",
    "Swimming Women's 4 x 200 metres Freestyle Relay",
    "Athletics Men's 10 kilometres Walk",
    "Athletics Women's 20 kilometres Walk",
    "Athletics Women's 80 metres Hurdles",
    "Sailing Men's One Person Heavyweight Dinghy",
    "Art Competitions Mixed Painting, Paintings",
    "Tennis Mixed Doubles, Covered Courts",
    "Cycling Men's Madison",
    "Art Competitions Mixed Sculpturing, Statues",
    "Rugby Men's Rugby",
    "Weightlifting Men's Heavyweight II",
    "Canoeing Women's Kayak Doubles, 500 metres",
    "Cycling Men's Individual Time Trial",
    "Judo Women's Heavyweight",
    "Canoeing Men's Kayak Doubles, 1,000 metres",
    "Gymnastics Men's Individual All-Around, 5 Events",
    "Wrestling Men's Super-Heavyweight, Freestyle",
    "Fencing Women's Sabre, Team",
    "Shooting Men's Double Trap",
    "Weightlifting Men's Bantamweight",
    "Taekwondo Men's Heavyweight",
    "Sailing Mixed Windsurfer",
    "Taekwondo Women's Welterweight",
    "Shooting Mixed Free Rifle, Three Positions, 300 metres",
    "Cycling Men's 50 kilometres",
    "Shooting Mixed Rapid-Fire Pistol, 25 metres",
    "Cycling Men's 333 metres Time Trial",
    "Cycling Men's 20 kilometres",
    "Canoeing Men's Kayak Singles, 10,000 metres",
    "Sailing Mixed Open",
    "Sailing Mixed 1-2 Ton",
    "Canoeing Men's Canadian Singles, Slalom",
    "Sailing Mixed Multihull",
    "Badminton Women's Doubles",
    "Diving Women's Synchronized Platform",
    "Athletics Women's Triple Jump",
    "Art Competitions Mixed Painting, Drawings And Water Colors",
    "Shooting Men's Dueling Pistol, 30 metres",
    "Boxing Women's Lightweight",
    "Cycling Women's BMX",
    "Canoeing Men's Kayak Doubles, 200 metres",
    "Fencing Men's Sabre, Masters, Individual",
    "Lacrosse Men's Lacrosse",
    "Canoeing Women's Kayak Singles, 500 metres",
    "Athletics Women's 10 kilometres Walk",
    "Sailing Mixed 12 metres",
    "Judo Women's Extra-Lightweight",
    "Diving Men's Synchronized Springboard",
    "Rowing Men's Coxed Fours, Outriggers",
    "Gymnastics Men's Rope Climbing",
    "Sailing Mixed Two Person Dinghy",
    "Art Competitions Mixed Architecture, Unknown Event",
    "Archery Men's Target Archery, 28 metres, Team",
    "Archery Men's Target Archery, 33 metres, Team",
    "Archery Men's Target Archery, 50 metres, Team",
    "Shooting Men's Running Target, 10 metres",
    "Polo Men's Polo",
    "Rowing Men's Coxed Fours, Inriggers",
    "Cycling Men's BMX",
    "Art Competitions Mixed Sculpturing",
    "Athletics Men's Cross-Country, Individual",
    "Athletics Men's Cross-Country, Team",
    "Sailing Mixed 40 metres",
    "Gymnastics Men's Club Swinging",
    "Tennis Women's Singles",
    "Tennis Mixed Doubles",
    "Tennis Women's Doubles",
    "Judo Women's Middleweight",
    "Judo Women's Lightweight",
    "Canoeing Women's Kayak Singles, 200 metres",
    "Canoeing Men's Kayak Relay 4 x 500 metres",
    "Athletics Men's 3,000 metres, Team",
    "Shooting Men's Small-Bore Rifle, Prone, 50 and 100 yards",
    "Shooting Men's Small-Bore Rifle, 50 and 100 yards, Team",
    "Shooting Men's Small-Bore Rifle, Disappearing Target, 25 yards",
    "Shooting Men's Small-Bore Rifle, Moving Target, 25 yards",
    "Shooting Men's Military Pistol, Team",
    "Rowing Women's Coxed Fours",
    "Weightlifting Men's Unlimited, One Hand",
    "Canoeing Men's Canadian Singles, 500 metres",
    "Fencing Men's Foil, Masters, Individual",
    "Fencing Men's epee, Masters, Individual",
    "Gymnastics Men's Individual All-Around, Field Sports",
    "Gymnastics Men's Individual All-Around, Apparatus Work",
    "Art Competitions Mixed Music, Compositions For Solo Or Chorus",
    "Fencing Women's epee, Team",
    "Swimming Men's 4,000 metres Freestyle",
    "Swimming Men's Underwater Swimming",
    "Sailing Mixed Skiff",
    "Shooting Men's Military Rifle, 200\/500\/600\/800\/900\/1,000 Yards, Team",
    "Shooting Men's Running Target, Single And Double Shot",
    "Shooting Men's Small-Bore Rifle, Any Position, 50 metres",
    "Shooting Men's Small-Bore Rifle, Disappearing Target, 25 metres",
    "Swimming Women's 10 kilometres Open Water",
    "Cycling Men's Team Pursuit, 1,980 yards",
    "Cycling Men's 5,000 metres",
    "Cycling Men's 100 kilometres",
    "Cricket Men's Cricket",
    "Canoeing Men's Canadian Singles, 10,000 metres",
    "Boxing Women's Middleweight",
    "Sailing Men's Skiff",
    "Athletics Men's Pentathlon",
    "Swimming Men's 1,200 metres Freestyle",
    "Shooting Women's Skeet",
    "Cycling Men's 1\/4 mile",
    "Cycling Men's 1\/2 mile",
    "Cycling Men's 5 mile",
    "Cycling Men's 25 mile",
    "Shooting Men's Small-Bore Rifle, Standing, 50 metres",
    "Shooting Men's Small Bore-Rifle, Standing, 50 metres, Team",
    "Shooting Men's Free Rifle, 1,000 Yards",
    "Cycling Women's Team Pursuit",
    "Athletics Men's 3,000 metres Walk",
    "Shooting Mixed Running Target, 50 metres",
    "Cycling Women's Individual Time Trial",
    "Fencing Women's Sabre, Individual",
    "Fencing Men's Sabre, Individual, Three Hits",
    "Archery Women's Double National Round",
    "Cycling Men's Omnium",
    "Equestrianism Mixed Hacks And Hunter Combined",
    "Sailing Mixed 10 metres",
    "Shooting Men's Trap, Team",
    "Cycling Women's Individual Pursuit, 3,000 metres",
    "Cycling Women's Points Race",
    "Sailing Men's Two Person Keelboat",
    "Cycling Men's Keirin",
    "Cycling Men's Team Sprint",
    "Athletics Men's 5 mile",
    "Shooting Men's Running Target, Single Shot, Team",
    "Ice Hockey Men's Ice Hockey",
    "Racquets Men's Singles",
    "Racquets Men's Doubles",
    "Art Competitions Mixed Literature, Lyric Works",
    "Motorboating Mixed A-Class (Open)",
    "Archery Men's Continental Style",
    "Art Competitions Mixed Painting, Graphic Arts",
    "Wrestling Women's Flyweight, Freestyle",
    "Art Competitions Mixed Literature, Unknown Event",
    "Sailing Mixed 0.5-1 Ton",
    "Art Competitions Mixed Painting, Applied Arts",
    "Croquet Mixed Singles, One Ball",
    "Croquet Mixed Doubles",
    "Shooting Men's Running Target, Double Shot, Team",
    "Shooting Men's Free Pistol, 50 yards",
    "Shooting Men's Free Pistol, 50 yards, Team",
    "Fencing Men's epee, Masters and Amateurs, Individual",
    "Swimming Men's 10 kilometres Open Water",
    "Art Competitions Mixed Music, Compositions For Orchestra",
    "Archery Men's Double York Round",
    "Wrestling Women's Middleweight, Freestyle",
    "Equestrianism Men's Vaulting, Individual",
    "Swimming Men's 4 x 250 metres Freestyle Relay",
    "Table Tennis Women's Team",
    "Athletics Women's Hammer Throw",
    "Canoeing Men's Kayak Singles, 200 metres",
    "Shooting Women's Double Trap",
    "Rowing Men's 6-Man Naval Rowing Boats",
    "Art Competitions Mixed Music",
    "Shooting Men's Free Rifle, Kneeling, 300 metres",
    "Shooting Men's Free Rifle, Prone, 300 metres",
    "Shooting Men's Free Rifle, Standing, 300 metres",
    "Athletics Men's 3,200 metres Steeplechase",
    "Rowing Women's Coxless Fours",
    "Tennis Men's Doubles, Covered Courts",
    "Tennis Men's Singles, Covered Courts",
    "Cycling Men's 25 kilometres",
    "Shooting Men's Military Rifle, 200 metres",
    "Athletics Men's Standing Triple Jump",
    "Rowing Men's Coxed Pairs (1 kilometres)",
    "Shooting Men's Military Pistol, 30 metres",
    "Cycling Women's Keirin",
    "Archery Men's Au Cordon Dore, 50 metres",
    "Figure Skating Men's Singles",
    "Figure Skating Mixed Pairs",
    "Swimming Women's 300 metres Freestyle",
    "Canoeing Men's Canadian Singles, 200 metres",
    "Sailing Mixed 30 metres",
    "Athletics Men's 4,000 metres Steeplechase",
    "Athletics Men's 5,000 metres, Team",
    "Rowing Men's Coxed Pairs (1 mile)",
    "Art Competitions Mixed Unknown Event",
    "Cycling Women's Omnium",
    "Swimming Men's 200 metres Obstacle Course",
    "Swimming Men's 200 metres Team Swimming",
    "Sailing Mixed 12 foot",
    "Art Competitions Mixed Music, Instrumental And Chamber",
    "Art Competitions Mixed Music, Vocals",
    "Art Competitions Mixed Literature, Dramatic Works",
    "Jeu De Paume Men's Singles",
    "Sailing Mixed 10-20 Ton",
    "Cycling Men's 1\/3 mile",
    "Cycling Men's 1 mile",
    "Cycling Men's 2 mile",
    "Art Competitions Mixed Sculpturing, Medals And Plaques",
    "Athletics Men's 1,600 metres Medley Relay",
    "Croquet Mixed Singles, Two Balls",
    "Canoeing Men's Folding Kayak Doubles, 10 kilometres",
    "Athletics Men's 60 metres",
    "Sailing Mixed 2-3 Ton",
    "Shooting Men's Military Rifle, Prone, 600 metres",
    "Canoeing Men's Canadian Doubles, 10,000 metres",
    "Shooting Men's Dueling Pistol, 30 metres, Team",
    "Gymnastics Men's Parallel Bars, Teams",
    "Gymnastics Men's Horizontal Bar, Teams",
    "Shooting Men's Small-Bore Rifle, Disappearing Target, 25 metres, Team",
    "Art Competitions Mixed Sculpturing, Medals And Reliefs",
    "Athletics Men's 1,500 metres Walk",
    "Athletics Men's 3 mile, Team",
    "Art Competitions Mixed Sculpturing, Medals",
    "Shooting Men's Military Rifle, Kneeling Or Standing, 300 metres",
    "Equestrianism Men's Vaulting, Team",
    "Shooting Men's Free Rifle, Any Position, 300 metres",
    "Shooting Men's Military Rifle, 1873-1874 Gras Model, Kneeling Or Standing, 200 metres",
    "Swimming Men's 100 Yard Backstroke",
    "Swimming Men's 440 Yard Breaststroke",
    "Art Competitions Mixed Literature, Epic Works",
    "Art Competitions Mixed Architecture",
    "Athletics Men's 3,500 metres Walk",
    "Roque Men's Singles",
    "Gymnastics Men's Side Horse",
    "Archery Men's Double American Round",
    "Archery Men's Team Round",
    "Archery Men's Target Archery, 33 metres, Individual",
    "Archery Men's Target Archery, 50 metres, Individual",
    "Swimming Men's 1,000 metres Freestyle",
    "Athletics Men's 10 mile Walk",
    "Athletics Men's Discus Throw, Both Hands",
    "Golf Men's Team",
    "Sailing Mixed 0-0.5 Ton",
    "Sailing Mixed 20+ Ton",
    "Cycling Women's Team Sprint",
    "Weightlifting Men's Unlimited, Two Hands",
    "Shooting Men's Free Pistol, 25 metres",
    "Shooting Men's Military Revolver, 1873-1874 Gras Model, 20 metres",
    "Shooting Men's Military Revolver, 20 metres",
    "Shooting Men's Dueling Pistol Au Vise 20 metres",
    "Shooting Men's Dueling Pistol Au Commandement, 25 metres",
    "Shooting Men's Small-Bore Rifle, Prone, 50 metres, Team",
    "Sailing Mixed 6.5 metres",
    "Athletics Men's 200 metres Hurdles",
    "Athletics Men's 56-pound Weight Throw",
    "Equestrianism Mixed Four-In-Hand Competition",
    "Athletics Men's 2,500 metres Steeplechase",
    "Art Competitions Mixed Music, Unknown Event",
    "Athletics Men's All-Around Championship",
    "Archery Men's Pole Archery, Small Birds, Individual",
    "Archery Men's Pole Archery, Large Birds, Individual",
    "Archery Men's Pole Archery, Small Birds, Team",
    "Archery Men's Pole Archery, Large Birds, Team",
    "Athletics Men's 2,590 metres Steeplechase",
    "Archery Women's Double Columbia Round",
    "Athletics Men's 4 mile, Team",
    "Figure Skating Men's Special Figures",
    "Shooting Men's Military Rifle, Standing, 300 metres",
    "Swimming Men's 50 yard Freestyle",
    "Swimming Men's 100 yard Freestyle",
    "Swimming Men's 440 yard Freestyle",
    "Basque Pelota Men's Two-Man Teams With Cesta",
    "Shooting Men's Trap, Single Shot, 16 metres",
    "Shooting Men's Trap, Double Shot, 14 metres",
    "Equestrianism Mixed Long Jump",
    "Canoeing Men's Folding Kayak Singles, 10 kilometres",
    "Shooting Men's Free Pistol, 30 metres",
    "Shooting Men's Military Pistol, 25 metres",
    "Swimming Men's 100 metres Freestyle For Sailors",
    "Archery Men's Sur La Perche a La Herse",
    "Sailing Mixed 3-10 Ton",
    "Gymnastics Men's Individual All-Around, 4 Events",
    "Alpinism Mixed Alpinism",
    "Wrestling Men's Unlimited Class, Greco-Roman",
    "Motorboating Mixed B-Class (Under 60 Feet)",
    "Motorboating Mixed C-Class",
    "Cycling Men's 10,000 metres",
    "Art Competitions Mixed Sculpturing, Reliefs",
    "Shooting Men's Muzzle-Loading Pistol, 25 metres",
    "Equestrianism Mixed High Jump",
    "Archery Men's Sur La Perche a La Pyramide",
    "Fencing Men's Single Sticks, Individual",
    "Figure Skating Women's Singles",
    "Gymnastics Men's Tumbling",
    "Shooting Men's Unknown Event",
    "Sailing Mixed 18 foot",
    "Archery Men's Unknown Event",
    "Archery Men's Au Chapelet, 50 metres",
    "Archery Men's Championnat Du Monde",
    "Archery Women's Team Round",
    "Wrestling Men's All-Around, Greco-Roman",
    "Cycling Men's 12-Hours Race",
    "Swimming Men's 500 metres Freestyle",
    "Weightlifting Men's All-Around Dumbbell Contest",
    "Archery Men's Au Chapelet, 33 metres",
    "Archery Men's Au Cordon Dore, 33 metres",
    "Archery Men's Target Archery, 28 metres, Individual",
    "Aeronautics Mixed Aeronautics",
    "Women's Road Race",
    "Women's Individual Time Trial",
    "Men's All-Around",
    "Men's Floor Exercise",
    "Men's Pommel Horse",
    "Men's Rings",
    "Men's Vault",
    "Men's Parallel Bars",
    "Men's Horizontal Bar",
    "Men's Team",
    "Men's Pair Team",
    "Men Team",
    "Women Team",
    "Lightweight Men's Double Sculls Team",
    "Men's 100m Breaststroke",
    "Women's Kumite +61kg",
    "Men's Greco-Roman 87kg",
    "Group All-Around Team",
    "Softball Team",
    "Men's 800m",
    "Men -73 kg",
    "10m Air Pistol Women",
    "10m Air Pistol Mixed Team",
    "10m Air Pistol Men",
    "Men -81 kg",
    "Men's Kumite -75kg",
    "Women's Team",
    "Men -66 kg",
    "Men's Freestyle 125kg",
    "Men's Javelin Throw",
    "Women -49kg",
    "Men's 3000m Steeplechase",
    "Men's Marathon",
    "Women's All-Around",
    "Women's Vault",
    "Women's Uneven Bars",
    "Women's Balance Beam",
    "Women's Floor Exercise",
    "Women's \u00c9p\u00e9e Individual",
    "Women's Singles",
    "Men's Heavy (81-91kg)",
    "Men's Freestyle 57kg",
    "Men's Greco-Roman 130kg",
    "Men's 73kg",
    "Men's Super Heavy (+91kg)",
    "Men's Individual",
    "Men's Light (57-63kg)",
    "Men's Freestyle 74kg",
    "Mixed Team",
    "Men's 400m Hurdles",
    "Women -52 kg",
    "Women's 3000m Steeplechase",
    "Men's Sabre Individual",
    "Men's Sabre Team",
    "Women's 3m Springboard",
    "Women's Synchronised 3m Springboard Team",
    "Men's Singles",
    "Men's 100m Freestyle",
    "Women's Skiff - 49er  Team",
    "Men's 5000m",
    "Women's 100m",
    "Men's Foil Individual",
    "Men's Foil Team",
    "Women's 76kg",
    "Women's 400m",
    "Men's Shot Put",
    "Men",
    "Men's 10km",
    "Women's Single Sculls",
    "Men's 1500m Freestyle",
    "Men's 4 x 400m Relay Team",
    "4 x 400m Relay Mixed Team",
    "Mixed 4 x 100m Medley Relay Team",
    "Men -68kg",
    "Mixed Doubles Team",
    "Skeet Men",
    "Men's Greco-Roman 97kg",
    "Men's 4 x 100m Freestyle Relay Team",
    "Women's Individual",
    "Women +67kg",
    "Men's 800m Freestyle",
    "Men's Kayak",
    "Men's Eight Team",
    "Women's 4 x 100m Relay Team",
    "Women -57kg",
    "Women's 100m Breaststroke",
    "Women's Shot Put",
    "Men's 96kg",
    "Women's Freestyle 76kg",
    "Men's 100m",
    "Women's Freestyle 57kg",
    "Women's Freestyle 62kg",
    "Individual All-Around",
    "Women +78 kg",
    "Women",
    "Men's Canoe Single 1000m",
    "Men's Canoe Double 1000m Team",
    "Men's Double Sculls Team",
    "Women's Quadruple Sculls Team",
    "Men's Two Person Dinghy - 470 Team",
    "Women's 1500m",
    "Men's 400m",
    "Women's 50m Freestyle",
    "Women -63 kg",
    "Men's Kayak Single 1000m",
    "Men's Triple Jump",
    "Men's Freestyle 86kg",
    "Men's 50km Race Walk",
    "Women -78 kg",
    "Women's Heptathlon",
    "Women's 10m Platform",
    "Women's Synchronised 10m Platform Team",
    "Men's Welter (63-69kg)",
    "Men's 100m Butterfly",
    "Women's Freestyle 68kg",
    "Men's 10,000m",
    "Women's Kayak Single 200m",
    "Women's Kayak Single 500m",
    "Men's Doubles Team",
    "Women's 4 x 100m Freestyle Relay Team",
    "Women's Pair Team",
    "Men's Greco-Roman 60kg",
    "Women's 49kg",
    "Men's Greco-Roman 77kg",
    "Men's 4 x 100m Relay Team",
    "10m Air Rifle Men",
    "50m Rifle 3 Positions Men",
    "Women's Freestyle 53kg",
    "25m Rapid Fire Pistol Men",
    "Men's High Jump",
    "Women's Welter (64-69kg)",
    "Men -60 kg",
    "Women's +87kg",
    "Men's Freestyle 65kg",
    "Men's Kayak Single 200m",
    "Men's Kumite +75kg",
    "Jumping Team",
    "Jumping Individual",
    "Trap Men",
    "Men's Single Sculls",
    "Men's Greco-Roman 67kg",
    "Men's Fly (48-52kg)",
    "Mixed Relay Team",
    "Men +80kg",
    "Mixed Multihull - Nacra 17 Foiling Team",
    "Women -57 kg",
    "Women's Eight Team",
    "Team",
    "Women's 59kg",
    "Women's 800m",
    "Men -80kg",
    "Duet Team",
    "Women's Light (57-60kg)",
    "Men's Light Heavy (75-81kg)",
    "Eventing Team",
    "Eventing Individual",
    "Women's Feather (54-57kg)",
    "Trap Women",
    "Trap Mixed Team",
    "Men's Feather (52-57kg)",
    "Men's 110m Hurdles",
    "Men's 81kg",
    "Baseball Team",
    "Men's 200m Breaststroke",
    "Women's Discus Throw",
    "Women's 4 x 400m Relay Team",
    "Men's Kumite -67kg",
    "Men's Road Race",
    "Men's Individual Time Trial",
    "Women's 4 x 200m Freestyle Relay Team",
    "Men's Kata",
    "Women's 100m Butterfly",
    "Women -67kg",
    "Men's 61kg",
    "Lightweight Women's Double Sculls Team",
    "Women -48 kg",
    "Men's 400m Freestyle",
    "Men's 200m Freestyle",
    "Women's Team Pursuit Team",
    "Men's Middle (69-75kg)",
    "Men's 200m",
    "Men's Skiff - 49er Team",
    "Women's 100m Hurdles",
    "Women's Marathon",
    "Women's Kata",
    "Men -90 kg",
    "Men's Hammer Throw",
    "Skeet Women",
    "Men's Individual Stroke Play",
    "Women's Hammer Throw",
    "Men's Park",
    "Women's 100m Freestyle",
    "Women's 200m Freestyle",
    "Women's 4 x 100m Medley Relay Team",
    "Women's 10km",
    "4 x 400m Relay Mixed",
    "Women's 20km Race Walk",
    "Women's 200m Individual Medley",
    "Women's 64kg",
    "Women's 10,000m",
    "Men's 1500m",
    "Women's Canoe Single 200m",
    "Women's Canoe Double 500m Team",
    "Women's Javelin Throw",
    "Men's 50m Freestyle",
    "Men's 200m Individual Medley",
    "Men's 4 x 100m Medley Relay Team",
    "Women's Sprint",
    "Women's Keirin",
    "Women's 87kg",
    "Men's 67kg",
    "Women's One Person Dinghy - Laser Radial",
    "Women's Four Team",
    "Men's Kayak Double 1000m Team",
    "Men's Kayak Four 500m Team",
    "Men's Quadruple Sculls Team",
    "Women's Team Sprint Team",
    "Women's Double Sculls Team",
    "Women's Sabre Individual",
    "Women's Sabre Team",
    "Men's Street",
    "Women's Doubles Team",
    "Men's 4 x 200m Freestyle Relay Team",
    "Women -70 kg",
    "Women's Long Jump",
    "Men's One Person Dinghy - Laser",
    "Women's Omnium",
    "Women's Madison Team",
    "Women's 100m Backstroke",
    "Men's 3m Springboard",
    "Men's 20km Race Walk",
    "Women's Kayak Double 500m Team",
    "Women's Two Person Dinghy - 470 Team",
    "Men's 10m Platform",
    "Women's Park",
    "Men's 100m Backstroke",
    "Men's 400m Individual Medley",
    "10m Air Rifle Women",
    "50m Rifle 3 Positions Women",
    "10m Air Rifle Mixed Team",
    "Men -58kg",
    "25m Pistol Women",
    "Men's +109kg",
    "Women's Individual Stroke Play",
    "Men's Windsurfer - RS:X",
    "Women's 4 x 100m Relay",
    "Men's 200m Backstroke",
    "Men's Cross-country",
    "Women's 200m Butterfly",
    "Men's Sprint",
    "Men's Keirin",
    "Dressage Team",
    "Dressage Individual",
    "Women's 200m",
    "Women's Foil Individual",
    "Women's Foil Team",
    "Women's 1500m Freestyle",
    "Men's 109kg",
    "Men's 200m Butterfly",
    "Women's 200m Backstroke",
    "Women's Kumite -55kg",
    "Men's Discus Throw",
    "Men's Synchronised 10m Platform Team",
    "Women's 400m Individual Medley",
    "Men's \u00c9p\u00e9e Individual",
    "Men's \u00c9p\u00e9e Team",
    "Women's Madison",
    "Men +100 kg",
    "Men's Decathlon",
    "Women's 5000m",
    "Women's Cross-country",
    "Women's Windsurfer - RS:X",
    "Women's 400m Hurdles",
    "Women's 200m Breaststroke",
    "Women's \u00c9p\u00e9e Team",
    "Women's 800m Freestyle",
    "Women's Pole Vault",
    "Women's Street",
    "Men's Canoe",
    "Men's Four Team",
    "Men's One Person Dinghy (Heavyweight) - Finn",
    "Men's Team Pursuit Team",
    "Men's Madison Team",
    "Women's Canoe",
    "Men's Long Jump",
    "Men's Team Sprint Team",
    "Men's Pole Vault",
    "Women's 400m Freestyle",
    "Women's Kayak Four 500m Team",
    "Men -100 kg",
    "Women's High Jump",
    "Women's Fly (48-51kg)",
    "Women's Kayak",
    "Women's Middle (69-75kg)",
    "Men's Synchronised 3m Springboard Team",
    "Women's Combined",
    "Women's 55kg",
    "Men's Combined",
    "Women's Kumite -61kg",
    "Men's 4 x 400m Relay",
    "Men's Omnium",
    "Men's Freestyle 97kg",
    "Women's Freestyle 50kg",
    "Women's Triple Jump",
    "Men's 4 x 100m Relay",
    "Women's 4 x 400m Relay",
    "Marathon Race Walk Relay Mixed",
    "Duet",
    "Men's +102kg",
    "Men's Kayak Single",
    "Men's Kayak Cross",
    "Men's 63.5kg",
    "Men's 71kg",
    "Women's Dinghy",
    "Women's Windsurfing",
    "Lightweight Men's Double Sculls",
    "Men's Synchronised 10m Platform",
    "Women's Synchronised 10m Platform",
    "Men's Synchronised 3m Springboard",
    "Group All-Around",
    "Women's Kayak Single",
    "Women's Kayak Cross",
    "Women's Kayak Double 500m",
    "Women's 60kg",
    "Women's 57kg",
    "Men's Kite",
    "Men's Dinghy",
    "Women's 4 x 100m Medley Relay",
    "Men's Speed",
    "Mixed Doubles",
    "Men's 89kg",
    "Men's 102kg",
    "Mixed Multihull",
    "Men's Windsurfing",
    "Women's Kite",
    "Skeet Mixed Team",
    "Lightweight Women's Double Sculls",
    "Men's Doubles",
    "Women's Doubles",
    "Women's 66kg",
    "Women's 4 x 100m Freestyle Relay",
    "Relay Only Athlete",
    "Men's 4 x 100m Medley Relay",
    "Women's Team Pursuit",
    "Women's Pair",
    "Women's Four",
    "Men's +92kg",
    "Women's 50kg",
    "Women's 54kg",
    "Men's 57kg",
    "Men's Canoe Double 500m",
    "B-Boys",
    "B-Girls",
    "Women's 81kg",
    "Women's 75kg",
    "Men's Skiff",
    "Men's Double Sculls",
    "Men's Pair",
    "Women's Double Sculls",
    "Women's 71kg",
    "Women's +81kg",
    "Men's Boulder & Lead",
    "Women's Boulder & Lead",
    "Men's Canoe Single",
    "Men's 92kg",
    "Men's Quadruple Sculls",
    "Men's Four",
    "Men's Eight",
    "Women's Eight",
    "Men's 51kg",
    "Women's Canoe Double 500m",
    "Women's Quadruple Sculls",
    "Women's Canoe Single",
    "Women's Team Sprint",
    "Women's Speed",
    "Men's 80kg",
    "Mixed Dinghy",
    "Women's Skiff",
    "Men's Madison",
    "Women's Kayak Four 500m",
    "Men's Kayak Four 500m",
    "Men's Kayak Double 500m",
    "Men's 4 x 100m Freestyle Relay",
    "Mixed 4 x 100m Medley Relay",
    "Men's Team Pursuit",
    "Women's 4 x 200m Freestyle Relay",
    "Men's Team Sprint",
    "Men's 4 x 200m Freestyle Relay",
    "Women's Synchronised 3m Springboard",
    "Mixed Relay"
];
  