export const olympicSports: string[] = [
  "Archery",
  "Artistic Swimming",
  "Athletics",
  "Badminton",
  "Basketball",
  "Boxing",
  "Canoeing",
  "Cycling",
  "Diving",
  "Equestrian",
  "Fencing",
  "Football",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hockey",
  "Judo",
  "Karate",
  "Modern Pentathlon",
  "Rowing",
  "Rugby Sevens",
  "Sailing",
  "Shooting",
  "Skateboarding",
  "Sport Climbing",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Triathlon",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Wrestling",
];
