AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iolap-llm-swagger

# Global Settings
Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  # API Gateway
  SwaggerServiceApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: v1-swagger
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # Lambda Functions
  SwaggerDocsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        ApiDocsEndpoint:
          Type: HttpApi
          Properties:
            Path: /api-docs
            Method: GET
            ApiId: !Ref SwaggerServiceApi
        SwaggerDocsEndpoint:
          Type: HttpApi
          Properties:
            Path: /swagger
            Method: GET
            ApiId: !Ref SwaggerServiceApi
        SwaggerStaticFiles:
          Type: HttpApi
          Properties:
            Path: /swagger/{proxy+}
            Method: GET
            ApiId: !Ref SwaggerServiceApi
    Metadata:
      BuildMethod: makefile

Outputs:
  SwaggerApi:
    Value: !Sub "https://${SwaggerServiceApi}.execute-api.${AWS::Region}.amazonaws.com/v1-swagger"
