name: Build And Test Sport Service Lambdas

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/sports/**"
      - ".github/workflows/build_and_test_sports_service.yaml"

env:
  AWS_REGION: "eu-central-1"
  SERVICE_PATH: "backend/sports"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Environment setups
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      # - name: Set up AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      # Preparing and running tests
      - name: Install dependencies for tests
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.SERVICE_PATH }}/tests/requirements.txt

      - name: Run tests
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          python -m unittest discover -s tests -p "test*.py" -v

      # Build service
      - name: Build service
        working-directory: ${{ env.SERVICE_PATH }}
        run: sam build --parallel --cached
